NUMPY BASICS : CODE-BASICS
1. PYTHON LIBRARY
2. THEY ARE USED FOR SCIENTIFIC COMPUTING 
3. NUMPY IS AN N-DIM ARRAY
4. WHEN COMPARED TO LIST NUMPY [takes less memory, fast, convinient]

Importing the Library

In [1]:
import numpy as np

In [2]:
# creating an array in numpy
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# comparing the SIZE of NUMPY & LIST
import sys
l = range(100)
print(sys.getsizeof(5)*len(l))
# 2800 : Reason size of 1 Array object is 14 Bytes
# Pointer are involved they redirect to another memory location taking more space 

2800


In [4]:
numpy_array = np.arange(100) # prints 0 - 99 numbers
print(numpy_array.size * numpy_array.itemsize)
# 400 

400


BASICS OPERATION OF NUMPY ARRAY

In [5]:
# Consider two numpy array
a = np.array([1,2,3])
b = a + 1
print(a,b) # [1 2 3] [2 3 4]

# Performing basics mathematical operations { + - * / % and ^}
print(a + b) # [3 5 7]
print(a - b) # [-1 -1 -1]
print(a * b) # [ 2  6 12]
print(a / b) # [0.5        0.66666667 0.75      ]
print(a % b) # [3 1 7]

# Performing Dot Product
print(a.dot(b)) # 20 [1*2 + 2*3 + 3*4]

[1 2 3] [2 3 4]
[3 5 7]
[-1 -1 -1]
[ 2  6 12]
[0.5        0.66666667 0.75      ]
[1 2 3]
20


CREATING A N-DIMENTIONAL ARRAY

In [14]:
# 1-d Array
a = np.array([1,2,3])
print(a.ndim)
# print(a)

# NOTE The Byte Size of Array
print(a.itemsize) # 4 :- 4 Cause Int

# 2-d Array
a = np.array([["A",1],["B",2]])
print(a.ndim)
# print(a)

# NOTE The Byte Size of Array
print(a.itemsize) # 44 :- Cause Str + Int

# n-d array / 3-dim
a = np.array([[[1,2.0],[3,4.0]],[[4,5.0],[6,7.0]]])
print(a.ndim)
# print(a)

# NOTE The Byte Size of Array
print(a.itemsize) # 8 :- Cause Float



1
4
2
4
3
8


CHECK DATATYPE

In [7]:
# To Check Datatype
a.dtype # dtype('float64')

# We can also change the Datatype
a.dtype = 'int32'
a.dtype # dtype('int32')

dtype('int32')

SIZE AND SHAPE

In [8]:
print(a.size) # 16 is the size 
print(a.shape) # 2 rows , 2 cols , 2 array

16
(2, 2, 4)


CREATING 0'S AND 1'S MATRIX

In [9]:
# all 1's matrix
o = np.ones((5,5))
print(o) # all 1 x 1 matrix

# all 0's matrix
z = np.zeros((5,5))
print(z) # all 0 x 0 matrix


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ARANGE

In [10]:
# Printing for a given range
a = np.arange(10)
print(a) # [0 1 2 3 4 5 6 7 8 9]

# Step Printing
a = np.arange(1,10,2)
print(a) # [1 3 5 7 9]

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


LINESPACE

In [11]:
a = np.linspace(1,5,10) # Generate 10 numbers btw 1 - 5
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


RESHAPE ARRAY & TRANSPOSE

In [12]:
a = np.array([[1,2,3,4],[5,6,7,8]])
# print(a)

# Reshapping Array
print(a)
print(a.shape)

# Reshape
a.reshape(4,2)

# NOTE TRANSPOSE
a.T

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

RAVEL : Function makes n-dim array into a 1-d array

In [13]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])