In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Slicing by giving range
a[0:4]

# NOTE Slicing index inverse
a[-1]

9

SLICEING USING A MULTI-DIM ARRAY

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,14,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 14, 12]])

SERIES OF ACCESSING THE MATRIX ELEMENT

In [19]:
# 1 row 2nd element  
a[1,2]
# 0 row 1 st element
a[0,1]
# all the rows from 0-1 print the 2nd element
a[:,2]
# all the rows last two col
a[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [14, 12]])

LOOPING THROUGH AN ARRAY

In [20]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 14, 12]])

In [26]:
for _ in a :
    print(_)

# NOTE but if we need an element which prints each element 
for i in a.flat:
    print(i) # NOTE we get all the element 

[1 2 3 4]
[5 6 7 8]
[ 9 10 14 12]
1
2
3
4
5
6
7
8
9
10
14
12
