NUMPY : CODEBASICS

In [2]:
# Library
import numpy as np

1. They are Python Library
2. They are used for Scientific computing 
3. The main objective of numpy is n-dim array
4. Why this compared to list ? 
- Less memory
- fast 
- Convinient 


# Basics Functions

In [3]:
# to create an array in numpy
np.array([1,2,3,4])

array([1, 2, 3, 4])

CHECKING THE SIZE OF NUMPY & LIST

In [4]:
# create a python list : range function
import sys
l = range(100)
print(sys.getsizeof(5) * len(l))
# Reason being size on 1 array object is 14 Bytes
# Pointer are involved that redirect to another memory location taking more space 

2800


In [5]:
n_array = np.arange(100)
print(n_array.size * n_array . itemsize)
# where as here its only 4 bytes,  this takes less memory and executes faster almost 10 times faster
# https://youtu.be/rN0TREj8G7U?list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU&t=507

400


BASICS OPERATIONS OF A NUMPY ARRAY

In [6]:
a = np.array([1,2,3])
b = np.array([3,4,5])
print(a+b, "add")
print(a-b,"sub")
print(a*b,"mul")
print(a/b,"div")
print(a%b,"mod")
print(a^b,'pow')
print(a.dot(b),'dot product')

[4 6 8] add
[-2 -2 -2] sub
[ 3  8 15] mul
[0.33333333 0.5        0.6       ] div
[1 2 3] mod
[2 6 6] pow
26 dot product


CREATING A 2-D / MULTI-DIMENSIONAL ARRAY

In [7]:
# 1-d array
a = np.array([1,2,3])

# to check the array-dim
print(a.ndim)

# 2-d array
b = np.array([["A",2,3],['B',5,6]])
print(b.ndim)

# multi-dim array
m = np.array([[[1.0,2.0],[3.0,4.0]],[[5.0,6.0],[7.0,8.0]]])
print(m.ndim)

1
2
3


In [8]:
print(a)
print("-----")
print(b)
print("-----")
print(m)

[1 2 3]
-----
[['A' '2' '3']
 ['B' '5' '6']]
-----
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


BYTE-SIZE OF EACH ELEMENT 

In [9]:
# to check the byte size
a.itemsize # : 4 cause INT
b.itemsize # : gives 44 STR + INT
m.itemsize # gives 8 FLOAT

8

TO CHECK THE DATATYPE

In [10]:
# check the datatype
a.dtype
# to change  the datatype
a.dtype = 'int32'
a.dtype = 'float16'
a.dtype

dtype('float16')

SIZE AND SHAPE -- IMPT

In [11]:
a.size # give  the number of element present 
a.shape # gives the number of Rows and Column (R x C)
m.shape # 2 matrix , 2 rows and 2 cols

(2, 2, 2)

CREATING MATRIX OF ZEROS AND ONES

In [12]:
# all zero matrix
a = np.zeros((3,2))
a
# all ones matrix
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

RANGE

In [13]:
# print number for given range 
a = np.arange(2)
a

# when you want steps like every 2 numbers
a = np.arange(1,10,2) # print every 2nd number from 1-10
a

array([1, 3, 5, 7, 9])

LINE SPACE

In [14]:
a = np.linspace(1,10,20) # btw the value of 1-10 it is generating 20 numbers
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

RESHAPING THE ARRAY : transpose or you can use reshape 

In [15]:
# b matrix
b
b.reshape(2,3)
b.reshape(6,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [16]:
b.T # APPLYING THE TRANSPOSE 

array([[1., 1., 1.],
       [1., 1., 1.]])

RAVEL FUNCITON TO FLATEN YOUR ARRAY : makes it into a 1-d array, but it dosent alter the original array

In [17]:
# matrix m
m

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [18]:
m.ravel() # makes the array completly flat make's it into one dimension

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Math Functions

In [19]:
# consider N-Dim array
a = np.array([[1,2,3,4],[5,6,7,8]])
a

# max function
a.max()

# min funciton
a.min()

# sum function
a.sum()

36

#### AXIS CONCEPT

In [20]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Axis 0 - Columns

In [21]:
a.sum(axis=0) # columns


array([ 6,  8, 10, 12])

Axis 1 - Rows

In [22]:
a.sum(axis=1) # rows 

array([10, 26])

SQRT

In [23]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

STANDARD DEVIATION FUNCITON

In [24]:
a.std()

2.29128784747792

# Slicing & Indexing of Numpy

#### INDEXING AND SLICING 

In [25]:
# Basic slicing 
n = np.array([1,2,3,4])
n[0:2]
# it will not cover 2

# cover -1 index : from last 
n[-1]

4

MULTI-DIMENSIONAL ARRAY

In [26]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,14,12]])
a
# 1 row 2nd element  
a[1,2]
# 0 row 1 st element
a[0,1]
# all the rows from 0-1 print the 2nd element
a[0:2,2]
# you can also do -ve index
a[-1,0:2]
# all the rows last two col
# (: it goes through all the rows )
a[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [14, 12]])

#### ITTERATE THROUGH AN ARRAY

In [27]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 14, 12]])

PRINTING ROWS : AND  " FLAT "  FOR ACCESSING ALL THE ELEMENT INSIDE AN ARRAY : works only on itteration

In [28]:
for row in a:
    print(row)

# sometime we flaten the list and print all the element
for cell in a.flat: # flat only works in np itteration
        print(cell)

[1 2 3 4]
[5 6 7 8]
[ 9 10 14 12]
1
2
3
4
5
6
7
8
9
10
14
12


#### STACKING ARRAYS

In [29]:
# creating two arrays
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7  8]
 [ 9 10 11]]


##### vstack ( Vertical stack [one-top-of-another] ) and hstack ( Horizontal Stack [side-by-side] )

In [30]:
# Imagin you are joining two data set 

# FOR VSTACK : IT MUST HAVE SAME NUMBER OF COL'S

# np.vstack((a,b)) # error , because of shape

a.shape
b = b.reshape(3,2)

print(np.vstack((a,b)))
print('---')
np.hstack((a,b))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
---


array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

##### NOW WE SPLIT THE ARRAY 

In [31]:
a = np.arange(30).reshape(2,15)
a
b = a
# now we split HORIZONTALLY
a = np.hsplit(a,3)
a
# now we split vertically 
b = np.vsplit(b,2)
b

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

##### BOOLEAN WITH ARRAY

In [32]:
a = np.arange(12).reshape(3,4) # this method is very common get used to it
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
b = a > 4
# here b is an one more array that is created on a condition
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
# pass b as an index to a and then take the true values numbers
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

THEY ARE ALSO USEFUL IN REPLACING

In [35]:
b = a > 5
a[b] = -1 # what ever true value you have got assaign it to -1
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])

# Array - Itteration

In [36]:
a = np.arange(20).reshape(5,4)
a
# for accessing all the rows
for rows in a:
    print(rows)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]


##### If you just want to flatten the matrix into an array just use a.flat() / a.flatten()

In [37]:
for rows in a.flatten():
# for rows in a.flat():
    print(rows)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


#### nditer : for iteration

In [38]:
for x in np.nditer(a,order='C'): # it does through Rowsise
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [39]:
for x in np.nditer(a,order='F'): # it does through Coloumwise
    print(x)

0
4
8
12
16
1
5
9
13
17
2
6
10
14
18
3
7
11
15
19


In [40]:
for x in np.nditer(a,order = 'F',flags=['external_loop']): # check for flag concept 
    print(x)

[ 0  4  8 12 16]
[ 1  5  9 13 17]
[ 2  6 10 14 18]
[ 3  7 11 15 19]


In [41]:
for x in np.nditer(a,order = 'F',op_flags=['readwrite']): # check for flag concept 
    x[...] = x * x
    print(x) # this will print the square the elemet in the array

0
16
64
144
256
1
25
81
169
289
4
36
100
196
324
9
49
121
225
361


#### Itterating through two arrays

Imagin you looping through two col's

In [42]:
a = np.arange(12).reshape(3,4)
b = np.arange(3).reshape(3,1)

# here we are traversalsing into two array 

for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
2 0
3 0
4 1
5 1
6 1
7 1
8 2
9 2
10 2
11 2


# Complete Numpy-Project

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('C:\\Users\\harip\\Desktop\\refrence\\data_science\\dataset\\taxi.csv')
df.head(1)

pickup_year  pickup_month  pickup_day  pickup_dayofweek  pickup_time  \
0         2016             1           1                 5            0   

   pickup_location_code  dropoff_location_code  trip_distance  trip_length  \
0                     2                      4           21.0         2037   

   fare_amount  fees_amount  tolls_amount  tip_amount  total_amount  \
0         52.0          0.8          5.54       11.65         69.99   

   payment_type  
0           1.0

In [3]:
df.shape

(46330, 15)

Questions : 
1. Avg speeeeed of all rides
2. Number of rides taken in FEB
3. Number of rides where trip is more than $50
4. Number of rides where drop was at JFK airport

In [4]:
df.columns

Index(['pickup_year', 'pickup_month', 'pickup_day', 'pickup_dayofweek',
       'pickup_time', 'pickup_location_code', 'dropoff_location_code',
       'trip_distance', 'trip_length', 'fare_amount', 'fees_amount',
       'tolls_amount', 'tip_amount', 'total_amount', 'payment_type'],
      dtype='object')

In [11]:
feb_count = df['pickup_month'] == 2
print('There are ',feb_count.sum(),'trip in FEB')

There are  13333 trip in FEB


In [15]:
fare50 = df['fare_amount'] > 50
print('There are',fare50.sum(),'rides which is more than 50$')

There are 15365 rides which is more than 50$
