In [1]:
from sys import version
print(version)

3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]


GFG : Coding Questions..

Find the index of the numbers whose sum is equal to the target      

In [7]:
# Index of sub-array sum
def sum_sub_array(array_list, target):
    if target in array_list: 
        print("target found",array_list.index(target))
    else:
        for i in range(len(array_list)):
            sum = 0
            for j in range(i, len(array_list)):
                sum+=array_list[j]
                if sum == target:
                    return i, j 
                
# Need More Attention..

In [10]:
a = [1,2,3,4,5,6]

sum_sub_array(a, 1) # Working as Expected!!
sum_sub_array(a, 20) # Working as Expected!!

target found 0


(1, 5)

Find the missing number in the array

In [270]:
def find_missing_value(array):
    empt_array = []
    if max(array) == 1:
        empt_array.append(2)
        print(f"Only 1 is present so the missing element is {empt_array}")
    else:
        max_value = max(array)
        for i in range(max_value, 0,  -1):
            empt_array.append(i)
            empt_array.sort()
        for i in empt_array:
            if i not in array:
                print(f"All the numbers from {min(array)} to {max(array)} are peresent except {i}")
                # print(empt_array)
                # print(array)

In [271]:
find_missing_value([1, 2, 3, 5]) # Working as Expected 
find_missing_value([8, 2, 4, 5, 3, 7, 1]) # Working as Expected
find_missing_value([1]) # Working as Expected

All the numbers from 1 to 5 are peresent except 4
All the numbers from 1 to 8 are peresent except 6
Only 1 is present so the missing element is [2]


Find the second largest element in an array

In [272]:
def find_second_larget(array):
    if min(array) == max(array):
        print(f"The largest element of the array is {max(array)} and the second largest element does not exist so {-1}.")
    else:
        array.sort(reverse = True)
        print(f"The largest element of the array is {array[0]} and the second largest element is {array[1]}")

In [273]:
find_second_larget([1,1,1,1,1,1])
find_second_larget([10,10,10,10])
find_second_larget([12, 35, 1, 10, 34, 1]) # Working as expected

The largest element of the array is 1 and the second largest element does not exist so -1.
The largest element of the array is 10 and the second largest element does not exist so -1.
The largest element of the array is 35 and the second largest element is 34


Kadane's Algo : Find the subset of an array with largest sum

- Not given any k-size

In [274]:
def largest_sub_array_sum(array):
    actual_array = []
    for i in array:
        if i > 0:
            actual_array.append(i)
            actual_array.sort(reverse=True)
    print(sum(actual_array))

In [275]:
largest_sub_array_sum([2, 3, -8, 7, -1, 2, 3]) # Largest sum of the sub-array

17


Free-Code-Camp

In [276]:
from sys import version
print(version) 

3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]


In [277]:
# Write a function to find the longest substring without repeating character

def longest_substring(string):
    string = string.split()
    
    # list
    non_repeating_char = [] 
    store_dict = {}
    empt_dict = {}

    for i in string:
        if i not in store_dict:
            store_dict[i] = len(i)

    # Finding the longest substring
    
    for key,values in store_dict.items():
        if values == max(store_dict.values()):
            print("The longest substring in the string is : ",key)

    # Finding the longest substring character 
    for i in string:
        if i not in empt_dict:
            empt_dict[i] = set(i)
    
    for value in empt_dict.values():
        if (value) == max(empt_dict.values()):
            print("The longest non-repeating substring is",value)
    
    return empt_dict

In [278]:
string = "hi my name is hariprasad"
a = longest_substring(string)

The longest substring in the string is :  hariprasad
The longest non-repeating substring is {'p', 'd', 'r', 'i', 'a', 'h', 's'}


In [279]:
# Given a list of integers return all combination that sums to the target
    # Need to work on this ..
            
def sum_target(list, target):
    initial_sum = 0
    for i in range(len(list)):
        if list[i] == target:
            print('Target Found in list at', i)
            break # Working as Intended
        else:
            initial_sum = list[i]
            for j in range(i,len(list)):
                initial_sum+=list[j]
                if initial_sum == target:
                    print('Target found')
                    break
                

In [280]:
sample_list = [1,2,3,4,5,6]
sum_target(sample_list, 2)

Target found
Target Found in list at 1


In [281]:
# Write a function to flatten a nested list ..
import numpy as np

a_list = np.array([[1,2,3],[4,5,6]])
print(a_list)

[[1 2 3]
 [4 5 6]]


In [282]:
for i in a_list:
    print(i)

[1 2 3]
[4 5 6]


Usage of Flatten

In [283]:
for i in a_list.flatten():
    print(i)

1
2
3
4
5
6


In [284]:
# Write a function to find the first non repeating character in a string / Find the non-repeating character in the string.

string = "hariprasad"

for i in string:
    if string.count(i) == 1:
        print(i)
        break
    elif string.count(i) > 1:
        pass

h


11.	1. Design a class to represent a bank account (deposit, withdraw, balance).
12.	2. Create a Restaurant Booking System (tables, customer, reservation).
13.	3. Use inheritance and polymorphism to create a shape class hierarchy (Shape → Circle, Rectangle,Square).


In [285]:
class bank:

    # My Initial Bal.
    balance = 0

    def __init__(self, name, age, branch):
        self.name = name
        self.age = age
        self.branch = branch

    def deposit(self, amount):
        self.balance+=amount
        print('Your Balance is', self.balance)

    def withdrawl(self,amount):
        if amount > self.balance:
            print('Amout exceed the balance')
        else:
            self.balance-=amount
            print(f"You avaliable balance is {self.balance} after withdrawing {amount} ")

    def getBalance(self):
        print(self.balance)

    def getInfo(self):
        print(f'''Name : {self.name}, Age : {self.age},  Branch : {self.branch}, Aval. Bal : {self.balance}''')
    

In [286]:
a_101 = bank(name="hari", age=24, branch='YPR')

In [287]:
a_101.getInfo()

Name : hari, Age : 24,  Branch : YPR, Aval. Bal : 0


In [288]:
a_101.getBalance()

0


In [289]:
a_101.deposit(amount=1000)

Your Balance is 1000


In [290]:
a_101.getBalance()

1000


In [291]:
a_101.withdrawl(amount=199)

You avaliable balance is 801 after withdrawing 199 


In [311]:
class Restaurant:
    def __init__(self, name, age):
        self.name = name
        self.age = age
        self.total_table = 100
        self.total_number_person_per_booking = 5
        self.reservation = False
        self.Flag = False

    def ac_status(self):
        if self.age > 20:
            print("Your Account is created")
            self.Flag = True
        else:
            print('Please call us at +91 0000-0000')

    def make_reservation(self):
        if self.Flag:
            number_of_tables = int(input('How many tables are you booking? '))
            if number_of_tables > self.total_table:
                print('Please call us for large group bookings.')
                print('Booking / Reservation Failed')
                self.reservation = False
            else:
                self.total_table -= number_of_tables
                self.reservation = True
                print(f'{number_of_tables} table(s) reserved successfully.')
        else:
            print('Please verify your account status first.')

    def book_for_me(self):
        number_of_people = int(input('Enter the number of people: '))
        if number_of_people > self.total_table * self.total_number_person_per_booking:
            print('Too many people for current seating.')
        else:
            print('You can walk in!')

    def confirmed(self):
        if self.Flag and self.reservation:
            print('Reservation is confirmed.')
        else:
            print('Reservation is not confirmed.')

In [314]:
a_110 = Restaurant("hari", 21)

In [315]:
a_110.ac_status()

Your Account is created


In [317]:
a_110.make_reservation()

2 table(s) reserved successfully.


In [318]:
a_110.confirmed()

Reservation is confirmed.


In [319]:
a_110.make_reservation()

Please call us for large group bookings.
Booking / Reservation Failed


In [320]:
a_110.confirmed()

Reservation is not confirmed.


In [321]:
# Polymorphism : Same function name but with different operation..

In [1]:
# Reverse a string
def rev(string):
    return string[::-1]

In [2]:
rev('hari')

'irah'

In [11]:
# Check if a given string is a palindrom

check_plaindrom = lambda x : print("Is Palindrom") if x == x[::-1] else print("Not Palindrom")
check_plaindrom('mom')
check_plaindrom('hari')

Is Palindrom
Not Palindrom


In [17]:
# Fibonacci Series Generator : 5 x 4 x 3 x 2 x 1
    # In Fibonacci series never give 0

def fibo_number(number):
    if number == 0 and number == 1:
        return 1
    else:
        fib = 1
        for i in range(number,1,-1):
            fib*=i
        print(fib)


In [18]:
fibo_number(5)

120


In [19]:
# Find the sum of n number
sum = 0
for i in range(10):
    sum+=i
print(sum)

45


In [1]:
# Find the largest number in a list 
a = [1,2,3,4,5,100,200,3,4,5,6,7,9,999,0,0,0,0,1,2,3,4,5,6,7,8]

# Way 1
print(max(a))

# Way 2
a.sort(reverse=True)
print(a[0])


999
999


In [4]:
# WAP to count the vowels in a string
def vowel_counter(string):
    empt_dict = {}
    vowel = ['a','e','i','o','u']
    for i in vowel:
        if i not in empt_dict:
            empt_dict[i] = string.count(i)
    return empt_dict

In [ ]:
vowel_counter(string = "hi my name is hariprasad and i am in ba ngalore, you can call me hari")

{'a': 11, 'e': 3, 'i': 6, 'o': 2, 'u': 1}

In [ ]:
# Find the missing number

# Assuming the list is an order array

sample_list = [1,2,3,5,6]
max_number = max(sample_list)
min_number = min(sample_list)
full_list = []
for i in range(min_number,max_number+1):
    if i not in full_list:
        full_list.append(i)

print(full_list)


# Another Method

full_list_2 = [x for x in range(min_number,max_number+1)]
full_list_2

[1, 2, 3, 4, 5, 6]


[1, 2, 3, 4, 5, 6]

In [33]:
# Flatten a nested list
sample_list = [[1,2,3],[4,5,6],[7,8,9]]
import numpy as np
sample_list = np.array(sample_list)
for i in sample_list.flatten():
    print(i)

1
2
3
4
5
6
7
8
9


In [40]:
# Finding the duplicates

a_sample_list = [1,1,1,3,4,5,7]
for i in a_sample_list:
    if a_sample_list.count(i) > 1: print(i)

1
1
1


In [58]:
# find the longest substring in a sentence
sentence = "hi my name is hariprasad and i am in ba bangalore, you can call me hariprasad"
length_of_words = [x for x in sentence.split()]
empt_dict = {}
for i in length_of_words:
    if i not in empt_dict:
        empt_dict[i] = len(i)

empt_dict



{'hi': 2,
 'my': 2,
 'name': 4,
 'is': 2,
 'hariprasad': 10,
 'and': 3,
 'i': 1,
 'am': 2,
 'in': 2,
 'ba': 2,
 'bangalore,': 10,
 'you': 3,
 'can': 3,
 'call': 4,
 'me': 2}

In [63]:
max_storer = []
for key,value in empt_dict.items():

    if value == max(empt_dict.values()):
        # This is the largest substing in the array
        max_storer.append(key)

In [66]:
print(max_storer[0])
# This the first logest substring in the sentence....

hariprasad


Got Questions from GPT

In [ ]:
# Reverse words in a Sentence
def reverse_sentence_word(sentence):
    return sentence.split()[::-1]
# This is the one way..

In [25]:
sentence = "Python is fun"
reverse_sentence_word(str(sentence))

['fun', 'is', 'Python']

In [33]:
# Rewored and got the thing
def reverse_sentence_word(sentence):
    empt_string = ""
    sentence = sentence.split()
    for i in range(len(sentence)-1,0-1,-1):
        empt_string+=sentence[i] + ' ' 
    return empt_string


reverse_sentence_word('Python is fun')

'fun is Python '

In [43]:
# Find the duplicates in list without set
sample_list = [1,2,2,3,4,5,5,6,7,7,8]
d_ele = {}

for i in sample_list:
    if i not in d_ele:
        d_ele[i] = 1
    else:
        d_ele[i]+=1

for key,value in d_ele.items():
    if value > 1:
        print(key)
        # 2, 5, 7 Are the numbers that are more than 1

2
5
7


In [44]:
set([x for x in sample_list if sample_list.count(x) > 1]) # If I convert this to a set 
# Using List Itteration

{2, 5, 7}

In [53]:
# Write a function to check if two list are anagram 
def check_anagram(string_one, string_two):
    word_one = [x for x in string_one]
    word_two = [x for x in string_two]
    word_one.sort(), word_two.sort()
    return 'Anagram' if word_two == word_one else 'Not Anagram'


In [61]:
check_anagram('listen','silent')
# check_anagram('','')

'Anagram'

In [ ]:
# Longest Substring in the given sentence

given_sentence = "Hi my name is hariprasad , I am from bangalore"
for i in given_sentence.split():
    if len(i) == max([len(x) for x in given_sentence.split()]):
        print(i)

hariprasad


In [ ]:
# Flatten this list 
a_list = [[1, 2, [3]], 4]
len(a_list)

# Need to work on this...

2

In [ ]:
# Using the map funciton 
a_list = [1,2,3,4]
def sample(x):
    return x * x # When you map it goes through the entire list

new_list = map(a_list, sample)

In [92]:
new_list = list(map(sample, a_list))
new_list

# Need to Learn this moreee..

[1, 4, 9, 16]

In [1]:
# Count the number of char freq. in a sting 
char_string = "hariprasad"
char_dict = {}
for i in char_string:
    if i not in char_dict:
        char_dict[i] = 1
    else:
        char_dict[i]+=1

char_dict


{'h': 1, 'a': 3, 'r': 2, 'i': 1, 'p': 1, 's': 1, 'd': 1}

In [125]:
# Create a log that store the argument passed to a function
log_list= []
def fun(word_one):
    
    if word_one in log_list:
        pass
    else:
        log_list.append(word_one)
        print(log_list)
    return len(word_one)


In [127]:
fun('hari')
fun('bangalore')
fun('hari prasad')
fun('hari') # Wont get appended in the list cause it alread exist, or i can just convert it to a sting 

4

In [133]:
# Prime number calculator
a = [x for x in range(1,12)]
result = ['Even' if x%2==0 else 'Odd' for x in a]
print(result)

['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd']


In [6]:
# sum of n-numbers using list itteration
sum([x for x in range(1,int(input('Enter the number')))])

45

03-MAY-2025