In [ ]:
import numpy as np

In [ ]:
a = np.arange(1,31).reshape(6,5)
a

ITTERATE THROUGH EACH ELEMENT THROUGH THE ARRAY

In [ ]:
for _ in a.flat:
    print(_) # NOTE option 1 prints all 30 element 

for _ in a.flatten():
    print(_) # NOTE option 2 prints all 30 element 

NDITER : FOR ITTERATION

In [23]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

LET US ITTERATE THROUGH ONLY ROWS 

In [ ]:
for _ in np.nditer(a,order = 'C'):
    print(_) # NOTE It does the same operation as flat , flatten()

COL'S WISE

In [22]:
for _ in np.nditer(a,order='F'):
    print(_)

0
5
10
15
1
6
11
16
2
7
12
17
3
8
13
18
4
9
14
19


In [25]:
for x in np.nditer(a,order = 'F',flags=['external_loop']): 
    print(x) # NOTE This changes the Order Col -> Rows

[ 0  5 10 15]
[ 1  6 11 16]
[ 2  7 12 17]
[ 3  8 13 18]
[ 4  9 14 19]


In [27]:
for _ in np.nditer(a,order = 'F', op_flags=['readwrite']):
    _ = _ * 2
    print(_)

0
10
20
30
2
12
22
32
4
14
24
34
6
16
26
36
8
18
28
38


ITTERATING THROUGH TWO ARRAYS

In [28]:
a = np.arange(12).reshape(3,4)
b = np.arange(3).reshape(3,1)

# here we are traversalsing into two array 

for x,y in np.nditer([a,b]):
    print(x,y)

0 0
1 0
2 0
3 0
4 1
5 1
6 1
7 1
8 2
9 2
10 2
11 2
