In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])

STATISTICAL FUNCTION

In [3]:
a.max() # 6
a.min() # 1
a.mean() # 3.5
a.std() # 1.707
a.sum() # 21
np.sqrt(a) # Gives the Sqrt Values of array elements 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

AXIS 0 : COLUMNS

In [5]:
a.sum(axis=0) # [1+4, 2+5, 3+6] 

array([5, 7, 9])

AXIS 1 : ROWS

In [6]:
a.sum(axis=1) # [1+4, 2+5, 3+6] 

array([ 6, 15])