In [3]:
import numpy as np

In [27]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


V STACK AND H STACK [ STACKING ]
* For performing a v-stack the number of col's must be same 

In [20]:
a.shape
b = b.reshape(3,4)
v = np.vstack((a,b))
print(v)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
h = np.hstack((a,b))
print(h)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [28]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

SAME AS STACK WE CAN EVNE SPLIT THE ARRAY

In [38]:
v = np.vsplit(a,3)
print(v)
h = np.hsplit(a,4)
print(h) # NOTE gives in a equal split

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


BOOLEAN WITH ARRAY

In [39]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b = a > 5
a[b] = -1 # NOTE which ever element is TRUE replace it with -1 (MEANING GREATER THAN 5)
a

array([[ 0,  1,  2,  3],
       [ 4,  5, -1, -1],
       [-1, -1, -1, -1]])